// ==UserScript==
// @name Vanderbilt Auto Proxy Redirector
// @namespace https://github.com/smasongarrison/Vanderbilt_Proxy_UserScript/raw/master/VU%20AutoProxy%20Redirector.user.js
// @description Automatically redirect to the proxified equivalent as provided by Vanderbilt University. Adapted from UWA Auto EzProxy Redirector (https://greasyfork.org/scripts/9907-uwa-auto-ezproxy-redirector/code/UWA%20Auto%20EzProxy%20Redirector.user.js)
// @version 0.2
// @license MIT
// @run-at document-start
// @grant none
// @update: https://github.com/smasongarrison/Vanderbilt_Proxy_UserScript/raw/master/VU%20AutoProxy%20Redirector.user.js

// @exclude *.proxy.library.vanderbilt.edu
// @match *://*.annualreviews.org/*
// @match *://*.aps.org/*
// @match *://*.biophysj.org/*
// @match *://*.blackwell-synergy.com/*
// @match *://*.bmjjournals.com/*
// @match *://*.informaworld.com/*
// @match *://*.ingentaconnect.com/*
// @match *://*.nature.com/*
// @match *://*.oxfordjournals.org/*
// @match *://*.portlandpress.co.uk/*
// @match *://*.portlandpress.com/*
// @match *://*.proteinscience.org/*
// @match *://*.sciencedirect.com/*
// @match *://*.sciencemag.org/*
// @match *://*.springer.com/*
// @match *://*.springerlink.com/*
// @match *://*.tandf.co.uk/*
// @match *://*.umi.com/*
// @match *://*.wiley.com/*
// @match *://*apc.org/*
// @match *://aapgbulletin.datapages.com/*
// @match *://access.ovid.com/*
// @match *://accessengineeringlibrary.com/*
// @match *://accesspharmacy.mhmedical.com/*
// @match *://acn.oxfordjournals.org/*
// @match *://acta.astrouw.edu.pl/*
// @match *://advisor.lww.com/*
// @match *://agdevjournal.com/*
// @match *://aids-clinical-care.jwatch.org/*
// @match *://ajcp.ascpjournals.org/*
// @match *://ajp.press.uiuc.edu/*
// @match *://alatechsource.metapress.com/*
// @match *://alcts.metapress.com/*
// @match *://alzres.com/*
// @match *://annals.princeton.edu/*
// @match *://antiquity.ac.uk/*
// @match *://app.pan.pl/*
// @match *://apps.brepolis.net/*
// @match *://apps.webofknowledge.com/*
// @match *://apsjournals.apsnet.org/*
// @match *://archive.scijournal.com/*
// @match *://archive.thewest.com.au/*
// @match *://archives.smh.com.au/*
// @match *://arthritis-research.com/*
// @match *://autoweb.rlg.org/*
// @match *://biblioline.nisc.com/*
// @match *://biomedicaloptics.spiedigitallibrary.org/*
// @match *://bjp.rcpsych.org/*
// @match *://bmc.lib.umich.edu/*
// @match *://books.igi-online.com/*
// @match *://breast-cancer-research.com/*
// @match *://brepols.metapress.com/*
// @match *://britishacademy.universitypressscholarship.com/*
// @match *://britishperiodicals.chadwyck.co.uk/*
// @match *://bst.portlandpress.com/*
// @match *://bww.dnb.com.au/*
// @match *://c19.chadwyck.co.uk/*
// @match *://caliber.ucpress.net/*
// @match *://ccforum.com/*
// @match *://cip.cornell.edu/*
// @match *://clients.ibisworld.com.au/*
// @match *://clinicalevidence.bmj.com/*
// @match *://clp.oxfordjournals.org/*
// @match *://cmo-devel.library.uwa.edu.au/*
// @match *://cmo.library.uwa.edu.au/*
// @match *://cognet.mit.edu/*
// @match *://collections.chadwyck.co.uk/*
// @match *://connect.jbiconnectplus.org/*
// @match *://connectweb.com.au/*
// @match *://content.apa.org/*
// @match *://content.iospress.com/*
// @match *://content.karger.com/*
// @match *://crl.acrl.org/*
// @match *://cs.portlandpress.com/*
// @match *://datanalysis.morningstar.com.au/*
// @match *://db.riskwaters.com/*
// @match *://dib.cambridge.org/*
// @match *://digitallibrary.sae.org/*
// @match *://dl.acm.org/*
// @match *://dlib.eastview.com/*
// @match *://dmfr.birjournals.org/*
// @match *://dx.doi.org/*
// @match *://ebooks.abc-clio.com/*
// @match *://ebooks.benthamscience.com/*
// @match *://ebooks.greenwood.com/*
// @match *://ebooks.hcn.com.au/*
// @match *://ebooks.spiedigitallibrary.org/*
// @match *://ebooks.worldscinet.com/*
// @match *://ecsdl.org/*
// @match *://edition.pagesuite-professional.co.uk/*
// @match *://eebo.chadwyck.com/*
// @match *://ejournals.wspc.com.sg/*
// @match *://elibrary.asabe.org/*
// @match *://enterprise.astm.org/*
// @match *://epress.monash.edu/*
// @match *://epubs.siam.org/*
// @match *://escarpmentpress.org/*
// @match *://estuariesandcoasts.org/*
// @match *://etg.tg.com.au/*
// @match *://eureka.rlg.org/*
// @match *://f1000.com/*
// @match *://find.galegroup.com/*
// @match *://flm-journal.org/*
// @match *://fordham.universitypressscholarship.com/*
// @match *://forms.library.uwa.edu.au/*
// @match *://genesdev.cshlp.org/*
// @match *://genomebiology.com/*
// @match *://genomemedicine.com/*
// @match *://geo.arizona.edu/*
// @match *://gerontologist.gerontologyjournals.org/*
// @match *://GIDEONonline.net/*
// @match *://glmu.alexanderstreet.com/*
// @match *://guilfordjournals.com/*
// @match *://heinonline.org/*
// @match *://henrystewart.metapress.com/*
// @match *://highwire.stanford.edu/*
// @match *://historicbrass.org/*
// @match *://histories.cambridge.org/*
// @match *://horttech.ashspublications.org/*
// @match *://hw.oeaw.ac.at/*
// @match *://hwwilsonweb.com/*
// @match *://iai.asm.org/*
// @match *://icsd.fiz-karlsruhe.de/*
// @match *://ieeexplore.ieee.org/*
// @match *://iimp.chadwyck.com/*
// @match *://iimpft.chadwyck.com/*
// @match *://incites.isiknowledge.com/*
// @match *://infotrac.galegroup.com/*
// @match *://intarch.ac.uk/*
// @match *://intelliconnect.wkasiapacific.com/*
// @match *://intl.alphamedpress.org/*
// @match *://intl.amjbot.org/*
// @match *://intl.iovs.org/*
// @match *://intl.jbc.org/*
// @match *://jada.ada.org/*
// @match *://jasn.asnjournals.org/*
// @match *://jchemed.chem.wisc.edu/*
// @match *://jco.ascopubs.org/*
// @match *://jds.fass.org/*
// @match *://jep.textrum.com/*
// @match *://jid.sagepub.com/*
// @match *://jmd.amjpathol.org/*
// @match *://jmpt.hcn.com.au/*
// @match *://jn.nutrition.org/*
// @match *://jorthod.maneyjournals.org/*
// @match *://journal.nzma.org.nz/*
// @match *://journal.telospress.com/*
// @match *://journalofrheology.org/*
// @match *://journals.ametsoc.org/*
// @match *://journals.asha.org/*
// @match *://journals.bcdecker.com/*
// @match *://journals.bmj.com/*
// @match *://journals.brepols.net/*
// @match *://journals.cambridge.org/*
// @match *://journals.cms.math.ca/*
// @match *://journals.informs.org/*
// @match *://journals.iucr.org/*
// @match *://journals.royalsociety.org/*
// @match *://journals.spiedigitallibrary.org/*
// @match *://journals.witpress.com/*
// @match *://journalsip.astm.org/*
// @match *://jrm.medicaljournals.se/*
// @match *://jwelb.oxfordjournals.org/*
// @match *://klapp-online.de/*
// @match *://knowledge.sagepub.com/*
// @match *://leme.library.utoronto.ca/*
// @match *://librariesaustralia.nla.gov.au/*
// @match *://library.cqpress.com/*
// @match *://library.pressdisplay.com/*
// @match *://library.seg.org/*
// @match *://librarymusicsource.com/*
// @match *://link.springer.com/*
// @match *://link.springer.de/*
// @match *://lion.chadwyck.co.uk/*
// @match *://llama.metapress.com/*
// @match *://login.westlaw.co.uk/*
// @match *://lupjournals.org/*
// @match *://materials.springer.com/*
// @match *://mcom.alexanderstreet.com/*
// @match *://msp.org/*
// @match *://muco.alexanderstreet.com/*
// @match *://multi-science.metapress.com/*
// @match *://muse.jhu.edu.au/*
// @match *://my.lawlex.com.au/*
// @match *://my.uwa.edu.au/*
// @match *://myrmecologicalnews.org/*
// @match *://nearmap.com/*
// @match *://nejm.highwire.org/*
// @match *://neoreviews.aappublications.org/*
// @match *://neur.allenpress.com/*
// @match *://new.sourceoecd.org/*
// @match *://newfirstsearch.oclc.org/*
// @match *://nijhoffonline.nl/*
// @match *://ojps.aip.org/*
// @match *://old.iias.asia/*
// @match *://online.factsandcomparisons.com/*
// @match *://online.liebertpub.com/*
// @match *://online.medphys.org/*
// @match *://online.sagepub.com/*
// @match *://onlinelibrary.wiley.com/*
// @match *://opil.ouplaw.com/*
// @match *://opticalengineering.spiedigitallibrary.org/*
// @match *://oversea.cnki.net/*
// @match *://ovidsp.ovid.com/*
// @match *://oxia.ouplaw.com/*
// @match *://pao.chadwyck.co.uk/*
// @match *://parlipapers.chadwyck.co.uk/*
// @match *://pci.chadwyck.com/*
// @match *://pediatrics.aappublications.org/*
// @match *://periodicals.narr.de/*
// @match *://philpapers.org/*
// @match *://physicsworldarchive.iop.org/*
// @match *://pio.chadwyck.co.uk/*
// @match *://piprofiler.systematics.net.au/*
// @match *://pjm.math.berkeley.edu/*
// @match *://plants.jstor.org/*
// @match *://poj.peeters-leuven.be/*
// @match *://portal.acm.org/*
// @match *://portal.igpublish.com/*
// @match *://press.endocrine.org/*
// @match *://products.asminternational.org/*
// @match *://projecteuclid.org/*
// @match *://ps.fass.org/*
// @match *://publications.epress.monash.edu/*
// @match *://publishing.monash.edu/*
// @match *://pubs.acs.org/*
// @match *://pubs.rsna.org/*
// @match *://pubservices.nrc-cnrc.ca/*
// @match *://quod.lib.umich.edu/*
// @match *://reference.sabinet.co.za/*
// @match *://referenceworks.brillonline.com/*
// @match *://repository.uwa.edu.au/*
// @match *://royalsocietypublishing.org/*
// @match *://sage-ereference.com/*
// @match *://scitation.aip.org/*
// @match *://search.alexanderstreet.com/*
// @match *://search.ebscohost.com/*
// @match *://search.informit.com.au/*
// @match *://search.micronexx.com/*
// @match *://search.proquest.com/*
// @match *://serials.abc-clio.com/*
// @match *://services.igi-global.com/*
// @match *://sex.sagepub.com/*
// @match *://sfaa.metapress.com/*
// @match *://shmu.alexanderstreet.com/*
// @match *://somme.library.uwa.edu.au/*
// @match *://sos.thieme.com/*
// @match *://spiedigitallibrary.aip.org/*
// @match *://spiedigitallibrary.org/*
// @match *://stahlonline.cambridge.org/*
// @match *://static.library.uwa.edu.au/*
// @match *://stemcellres.com/*
// @match *://stephanus.tlg.uci.edu/*
// @match *://subscriber.lawbookco.com.au/*
// @match *://tax.thomsonreuters.com.au/*
// @match *://technopress.kaist.ac.kr/*
// @match *://thephilosophersmagazine.com/*
// @match *://theses.library.uwa.edu.au/*
// @match *://tl2.idcpublishers.info/*
// @match *://tla.thomson.com.au/*
// @match *://transactionpub.metapress.com/*
// @match *://trb.metapress.com/*
// @match *://turf.lib.msu.edu/*
// @match *://ulrichsweb.serialssolutions.com/*
// @match *://universitypublishingonline.org/*
// @match *://untreaty.un.org/*
// @match *://utpjournals.metapress.com/*
// @match *://uwa.cambridge.patron.eb20.com/*
// @match *://uwa.eblib.com.au/*
// @match *://uwa.kanopystreaming.com/*
// @match *://uwa.naxosmusiclibrary.com/*
// @match *://uwa.naxosvideolibrary.com/*
// @match *://uwau.classical.com/*
// @match *://vlearn.vea.com.au/*
// @match *://vnweb.hwwilsonweb.com/*
// @match *://web.ovid.unilinc.edu.au/*
// @match *://web5s.silverplatter.com/*
// @match *://webofknowledge.com/*
// @match *://wellesley.chadwyck.co.uk/*
// @match *://westlaw.com.au/*
// @match *://wileyonlinelibrary.com/*
// @match *://wlt.metapress.com/*
// @match *://worldcatlibraries.org/*
// @match *://ww3.cch.com.au:8080/*
// @match *://www-thejns-net.org/*
// @match *://www.aacc.org/*
// @match *://www.aacr.org/*
// @match *://www.aacrjournals.org/*
// @match *://www.aacrmeetingabstracts.org/*
// @match *://www.aaiddjournals.org/*
// @match *://www.aanda.org/*
// @match *://www.aapm.org/*
// @match *://www.abcb.gov.au/*
// @match *://www.abs.gov.au/*
// @match *://www.accessmedicine.com/*
// @match *://www.acta.hu/*
// @match *://www.actahort.org/*
// @match *://www.actamathematica.org/*
// @match *://www.adtmag.com/*
// @match *://www.aeaweb.org/*
// @match *://www.afpe.org.uk/*
// @match *://www.african-archaeology.de/*
// @match *://www.agronomy.org/*
// @match *://www.agu.org/*
// @match *://www.ahajournals.org/*
// @match *://www.aiaa.org/*
// @match *://www.ajcn.org/*
// @match *://www.ajhg.org/*
// @match *://www.ajsonline.org/*
// @match *://www.ajtmh.org/*
// @match *://www.akademiai.com/*
// @match *://www.amamanualofstyle.com/*
// @match *://www.amjpathol.org/*
// @match *://www.ams.org/*
// @match *://www.anesthesiaprogress.org/*
// @match *://www.annallergy.org/*
// @match *://www.annals.org/*
// @match *://www.annee-philologique.com/*
// @match *://www.annualreviews.org/*
// @match *://www.anthrosource.net/*
// @match *://www.arabidopsis.org/*
// @match *://www.architecture.com.au/*
// @match *://www.artstor.org/*
// @match *://www.asadl.org/*
// @match *://www.asbmb.org/*
// @match *://www.ascb.org/*
// @match *://www.ascelibrary.org/*
// @match *://www.asia-studies.com/*
// @match *://www.asihcopeiaonline.org/*
// @match *://www.asip.org/*
// @match *://www.aslo.org/*
// @match *://www.asm.org/*
// @match *://www.asmedigitalcollection.asme.org/*
// @match *://www.asmjournals.org/*
// @match *://www.asn-online.org/*
// @match *://www.aspectfinancial.com.au/*
// @match *://www.aspetjournals.org/*
// @match *://www.aspresolver.com/*
// @match *://www.astreetpress.com/*
// @match *://www.atilf.fr/*
// @match *://www.atsjournals.org/*
// @match *://www.atypon-link.com/*
// @match *://www.austlit.edu.au/*
// @match *://www.austms.org.au/*
// @match *://www.australianmusiccentre.com.au/*
// @match *://www.bcaillustrated.com.au/*
// @match *://www.begellhouse.com/*
// @match *://www.bepress.com/*
// @match *://www.biochemj.org/*
// @match *://www.biochemsoctrans.org/*
// @match *://www.biolbull.org/*
// @match *://www.biologists.com/*
// @match *://www.biologists.org/*
// @match *://www.biolreprod.org/*
// @match *://www.biomedcentral.com/*
// @match *://www.biophysj.org/*
// @match *://www.bioscientifica.com/*
// @match *://www.blackwell-synergy.com/*
// @match *://www.blackwellreference.com/*
// @match *://www.bloodjournal.org/*
// @match *://www.brepolis.net/*
// @match *://www.bridgemaneducation.com/*
// @match *://www.brillonline.nl/*
// @match *://www.businessnews.com.au/*
// @match *://www.butterworthsonline.com/*
// @match *://www.caaa.ca/*
// @match *://www.cababstractsplus.org/*
// @match *://www.cabdirect.org/*
// @match *://www.cabi.org/*
// @match *://www.canmin.org/*
// @match *://www.ceda.com.au/*
// @match *://www.cefc.com.hk/*
// @match *://www.cellbiolint.org/*
// @match *://www.cellpress.com/*
// @match *://www.charlestonco.com/*
// @match *://www.chelonianjournals.org/*
// @match *://www.chemnetbase.com/*
// @match *://www.chicagomanualofstyle.org/*
// @match *://www.citiprogram.org/*
// @match *://www.classiques-garnier.com/*
// @match *://www.clinchem.org/*
// @match *://www.clinicalevidence.org/*
// @match *://www.clinicalkey.com/*
// @match *://www.cmaj.ca/*
// @match *://www.comlaw.gov.au/*
// @match *://www.communicationencyclopedia.com/*
// @match *://www.computerworld.com.au/*
// @match *://www.connect4.com.au/*
// @match *://www.connectweb.com.au/*
// @match *://www.cortex-online.org/*
// @match *://www.crcnetbase.com/*
// @match *://www.credoreference.com/*
// @match *://www.cro3.org/*
// @match *://www.csa.com/*
// @match *://www.csa3.com/*
// @match *://www.csj.jp/*
// @match *://www.csu.edu.au/*
// @match *://www.current-reports.com/*
// @match *://www.datagold.com/*
// @match *://www.datamonitor.com/*
// @match *://www.datatrace.com/*
// @match *://www.dbpia.co.kr/*
// @match *://www.degruyter.com/*
// @match *://www.dental-update.co.uk/*
// @match *://www.dialogatsite.com/*
// @match *://www.dictionaryofeconomics.com/*
// @match *://www.digitaleditions.com.au/*
// @match *://www.dukejournals.org/*
// @match *://www.dukemathjournal.org/*
// @match *://www.dukeupress.edu/*
// @match *://www.e-enlightenment.com/*
// @match *://www.earthmagazine.org/*
// @match *://www.ebmonline.org/*
// @match *://www.economist.com/*
// @match *://www.edata-center.com/*
// @match *://www.editlib.org/*
// @match *://www.edpsciences.org/*
// @match *://www.edrs.com/*
// @match *://www.educause.edu/*
// @match *://www.ejbjs.org/*
// @match *://www.eje-online.org/*
// @match *://www.electrochem.org/*
// @match *://www.elgaronline.com/*
// @match *://www.emeraldinsight.com/*
// @match *://www.empire.amdigital.co.uk/*
// @match *://www.ems-ph.org/*
// @match *://www.endocrinology-journals.org/*
// @match *://www.engineeringvillage.com/*
// @match *://www.engnetbase.com/*
// @match *://www.envplan.com/*
// @match *://www.eolss.net/*
// @match *://www.equinoxpub.com/*
// @match *://www.erj.ersjournals.com/*
// @match *://www.erudit.org/*
// @match *://www.esajournals.org/*
// @match *://www.escj.org/*
// @match *://www.euppublishing.com/*
// @match *://www.europaworld.com/*
// @match *://www.europhysicsnews.org/*
// @match *://www.evolutionary-ecology.com/*
// @match *://www.exacteditions.com/*
// @match *://www.expertconsultbook.com/*
// @match *://www.fasebj.org/*
// @match *://www.finsia.com/*
// @match *://www.fq.math.ca/*
// @match *://www.fupress.net/*
// @match *://www.futuremedicine.com/*
// @match *://www.gendatabaseonline.com/*
// @match *://www.gender.amdigital.co.uk/*
// @match *://www.genetics.org/*
// @match *://www.geoscienceworld.org/*
// @match *://www.groundimprovement.com/*
// @match *://www.hartjournals.co.uk/*
// @match *://www.hbcpnetbase.com/*
// @match *://www.hcn.net.au/*
// @match *://www.hematology.org/*
// @match *://www.heterocycles.jp/*
// @match *://www.hh.um.es/*
// @match *://www.hhpr.org/*
// @match *://www.hljournals.org/*
// @match *://www.hstalks.com/*
// @match *://www.hub.sciverse.com/*
// @match *://www.humanitiesebook.org/*
// @match *://www.i-law.com/*
// @match *://www.iaglr.org/*
// @match *://www.icevirtuallibrary.com/*
// @match *://www.igi-online.com/*
// @match *://www.iias.nl/*
// @match *://www.iijournals.com/*
// @match *://www.ijdb.ehu.es/*
// @match *://www.ijee.dit.ie/*
// @match *://www.ijocs.org/*
// @match *://www.imf.org/*
// @match *://www.imfareaer.org/*
// @match *://www.imfstatistics.org/*
// @match *://www.inderscienceonline.com/*
// @match *://www.indiaraj.amdigital.co.uk/*
// @match *://www.informahealthcare.com/*
// @match *://www.informaworld.com/*
// @match *://www.infosci-books.com/*
// @match *://www.ingentaconnect.com/*
// @match *://www.ingentaselect.com/*
// @match *://www.intlpress.com/*
// @match *://www.intmedpress.com/*
// @match *://www.iop.org/*
// @match *://www.ipasource.com/*
// @match *://www.ishib.org/*
// @match *://www.itergateway.org/*
// @match *://www.iumj.indiana.edu/*
// @match *://www.iwaponline.com/*
// @match *://www.jabfp.org/*
// @match *://www.japmaonline.org/*
// @match *://www.jbmronline.com/*
// @match *://www.jdentaled.org/*
// @match *://www.jem.org/*
// @match *://www.jhortscib.org/*
// @match *://www.jimmunol.org/*
// @match *://www.jleukbio.org/*
// @match *://www.jlr.org/*
// @match *://www.jmecology.com/*
// @match *://www.jnabs.org/*
// @match *://www.jneurosci.org/*
// @match *://www.jnrlse.org/*
// @match *://www.joannabriggs.edu.au/*
// @match *://www.jomms.org/*
// @match *://www.jopdentonline.org/*
// @match *://www.joponline.org/*
// @match *://www.jospt.org/*
// @match *://www.journalofanimalscience.org/*
// @match *://www.journalofgreenbuilding.com/*
// @match *://www.journalofphilosophy.org/*
// @match *://www.journals.uchicago.edu/*
// @match *://www.journalsleep.org/*
// @match *://www.jove.com/*
// @match *://www.jrheum.com/*
// @match *://www.jrheum.org/*
// @match *://www.jsad.com/*
// @match *://www.jstage.jst.go.jp/*
// @match *://www.jstor.org/*
// @match *://www.jultrasoundmed.org/*
// @match *://www.justcite.com/*
// @match *://www.justis.com/*
// @match *://www.kappanmagazine.org/*
// @match *://www.karger.com/*
// @match *://www.kluwerarbitration.com/*
// @match *://www.kluwerlawonline.com/*
// @match *://www.kluweronline.com/*
// @match *://www.knovel.com/*
// @match *://www.labanimal.com/*
// @match *://www.law.usyd.edu.au/*
// @match *://www.lcoastpress.com/*
// @match *://www.lexisnexis.com.au/*
// @match *://www.lexxion.eu/*
// @match *://www.libraryedition.com.au/*
// @match *://www.litencyc.com/*
// @match *://www.literatureencyclopedia.com/*
// @match *://www.londonlowlife.amdigital.co.uk/*
// @match *://www.lrb.co.uk/*
// @match *://www.lyellcollection.org/*
// @match *://www.macquariedictionary.com.au/*
// @match *://www.maneyonline.com/*
// @match *://www.math.uh.edu/*
// @match *://www.mathjournals.org/*
// @match *://www.mathnetbase.com/*
// @match *://www.mathscipub.org/*
// @match *://www.mcponline.org/*
// @match *://www.medicalevidencematters.com/*
// @match *://www.medici.tv/*
// @match *://www.medicinescomplete.com/*
// @match *://www.mergentonline.com/*
// @match *://www.metapress.com/*
// @match *://www.micromedexsolutions.com/*
// @match *://www.mimsonline.com.au/*
// @match *://www.minsocam.org/*
// @match *://www.mitpressjournals.org/*
// @match *://www.mja.com.au/*
// @match *://www.mlajournals.org/*
// @match *://www.morganclaypool.com/*
// @match *://www.mrlonline.org/*
// @match *://www.msa.org.au/*
// @match *://www.museumoftheearth.org/*
// @match *://www.musicforum.org.au/*
// @match *://www.myilibrary.com/*
// @match *://www.nature.com/*
// @match *://www.nber.org/*
// @match *://www.ncbi.nlm.nih.gov/*
// @match *://www.neilsonjournals.com/*
// @match *://www.nejm.org/*
// @match *://www.newleftreview.org/*
// @match *://www.nowpublishers.com/*
// @match *://www.nrcresearchpress.com/*
// @match *://www.nursingreview.com.au/*
// @match *://www.nybooks.com/*
// @match *://www.oceanalaw.com/*
// @match *://www.oecd-ilibrary.org/*
// @match *://www.oecd-nea.org/*
// @match *://www.oecdobserver.org/*
// @match *://www.oed.com/*
// @match *://www.oldcitypublishing.com/*
// @match *://www.oldenbourg-link.com/*
// @match *://www.onarchitecture.com/*
// @match *://www.onemine.org/*
// @match *://www.onlinepublications.austroads.com.au/*
// @match *://www.openbookpublishers.com/*
// @match *://www.opticsinfobase.org/*
// @match *://www.opuluspress.se/*
// @match *://www.orchestralmusic.com/*
// @match *://www.oxford-auslawdictionary.com/*
// @match *://www.oxford-economichistory.com/*
// @match *://www.oxford-humanrights.com/*
// @match *://www.oxford-naswsocialwork.com/*
// @match *://www.oxford-theatreandperformance.com/*
// @match *://www.oxfordartonline.com/*
// @match *://www.oxfordbibliographies.com/*
// @match *://www.oxforddnb.com/*
// @match *://www.oxfordhandbooks.com/*
// @match *://www.oxfordjournals.org/*
// @match *://www.oxfordmusiconline.com/*
// @match *://www.oxfordreference.com/*
// @match *://www.oxfordscholarship.com/*
// @match *://www.oxfordwesternmusic.com/*
// @match *://www.pacificarchaeology.org/*
// @match *://www.palgrave-journals.com/*
// @match *://www.pdcnet.org/*
// @match *://www.perceptionweb.com/*
// @match *://www.pharmacopoeia.co.uk/*
// @match *://www.phycologia.org/*
// @match *://www.physiology.org/*
// @match *://www.physsportsmed.com/*
// @match *://www.pidgeondigital.com/*
// @match *://www.pkulaw.cn/*
// @match *://www.plantcell.org/*
// @match *://www.plantphysiol.org/*
// @match *://www.pnas.org/*
// @match *://www.polymersdatabase.com/*
// @match *://www.portal.euromonitor.com/*
// @match *://www.presidian.com.au/*
// @match *://www.press.uillinois.edu/*
// @match *://www.proteinscience.org/*
// @match *://www.psychiatrist.com/*
// @match *://www.psychiatryonline.org/*
// @match *://www.psychonomic-journals.org/*
// @match *://www.publichealthreports.org/*
// @match *://www.publish.csiro.au/*
// @match *://www.rangelands.org/*
// @match *://www.rbgkew.org.uk/*
// @match *://www.rep.routledge.com/*
// @match *://www.reproduction-online.org/*
// @match *://www.researcherid.com/*
// @match *://www.revues.armand-colin.com/*
// @match *://www.rockefeller.edu/*
// @match *://www.romanticism.amdigital.co.uk/*
// @match *://www.rsc.org/*
// @match *://www.rsnz.org/*
// @match *://www.rupress.org/*
// @match *://www.saiglobal.com/*
// @match *://www.sanbi.co.jp/*
// @match *://www.sauerlaender-verlag.com/*
// @match *://www.schattauer.de/*
// @match *://www.sciandmed.com/*
// @match *://www.sciencedirect.com/*
// @match *://www.sciencemag.org/*
// @match *://www.scientific.net/*
// @match *://www.sciquest.org.nz/*
// @match *://www.scopus.com/*
// @match *://www.sgm.ac.uk/*
// @match *://www.shancocksltd.co.uk/*
// @match *://www.sif.it/*
// @match *://www.sjmjournals.org/*
// @match *://www.sleepmedtext.com/*
// @match *://www.sloan-c.org/*
// @match *://www.sociologyencyclopedia.com/*
// @match *://www.spe.org/*
// @match *://www.srmjournals.org/*
// @match *://www.ssr.org/*
// @match *://www.stat.sinica.edu.tw/*
// @match *://www.stata-journal.com/*
// @match *://www.statindex.org/*
// @match *://www.statistics.gov.uk/*
// @match *://www.surgeryjournal.co.uk/*
// @match *://www.tandfonline.com/*
// @match *://www.terrapub.co.jp/*
// @match *://www.the-aps.org/*
// @match *://www.theannals.com/*
// @match *://www.thelancet.com/*
// @match *://www.theshakespearerecords.com/*
// @match *://www.thomastelford.com/*
// @match *://www.tlemea.com/*
// @match *://www.triangle.co.uk/*
// @match *://www.trrjournalonline.trb.org/*
// @match *://www.turpion.org/*
// @match *://www.universitypressscholarship.com/*
// @match *://www.update-software.com/*
// @match *://www.uwpress.org/*
// @match *://www.v-r.de/*
// @match *://www.victoriandatabase.com/*
// @match *://www.victorianperiodicals.com/*
// @match *://www.waspress.co.uk/*
// @match *://www.webofknowledge.com/*
// @match *://www.westlaw.com/*
// @match *://www.withoutsanctuary.org/*
// @match *://www.worldbank.org/*
// @match *://www.worldscientific.com/*
// @match *://www.worldscinet.com/*
// @match *://www.worldshakesbib.org/*
// @match *://www.wssajournals.org/*
// @match *://www.yale.edu/*
// @match *://www3.griffith.edu.au/*
// @match *://xroads.virginia.edu/*
// ==/UserScript==

window.location.replace ("https://proxy.library.vanderbilt.edu/login?url="+window.location.href);

